#pragma once

#include "cbe/builder.hpp"
#include "cbe/graph.hpp"
#include "cbe/utility.hpp"
#if FF_cbe__estimates
#include "cbe/work_estimate.hpp"
#endif

#include <shared_mutex>
#include <string>
#include <thread>
#include <vector>

namespace catalyst {

struct JSON;

struct ToolchainFlags {
    const std::vector<std::string> &cc;
    const std::vector<std::string> &cxx;
    const std::vector<std::string> &cflags;
    const std::vector<std::string> &cxxflags;
    const std::vector<std::string> &ldflags;
    const std::vector<std::string> &ldlibs;
};

/**
 * @brief Thread-safe cache for file status information (modification times).
 *
 * This cache prevents redundant filesystem calls when checking multiple dependencies
 * for the same file across different threads.
 */
class StatCache {
    struct Entry {
        std::filesystem::path path;
        std::filesystem::file_time_type time;
        std::error_code ec;

        bool operator<(const Entry &other) const;
        bool operator<(const std::filesystem::path &other_path) const;
    };

    std::vector<Entry> cache;
    std::shared_mutex cache_mtx;

public:
    /**
     * @brief Retrieves the last write time for a path, caching the result.
     * @param p The file path to check.
     * @return A pair containing the last write time and any error code.
     */
    std::pair<std::filesystem::file_time_type, std::error_code> get_or_update(const std::filesystem::path &p);

    /**
     * @brief Checks if an input file has changed since a given output timestamp.
     * @param input The input file path.
     * @param output_time The timestamp of the output file.
     * @return True if input is newer or stat failed, false otherwise.
     */
    bool changed_since(const std::filesystem::path &input, std::filesystem::file_time_type output_time);

    /**
     * @brief Returns the number of entries in the cache (primarily for unit tests).
     */
    size_t get_cache_size() const;
};

struct ExecutorConfig {
    bool dry_run = false;                              ///< If true, print commands without executing.
    bool clean = false;                                ///< If true, clean artifacts instead of building.
    bool clean_cc_only = false;                        ///< If true, only clean cc and cxx steps.
    bool silent = false;                               ///< If true, suppress all output except errors.
    bool keep_going = false;                            ///< If true, continue building other steps after an error.
    size_t jobs = 0;                                   ///< Number of parallel jobs (0 = auto-detect).
    std::string build_file = "catalyst.build";         ///< Path to the build manifest.
#if FF_cbe__estimates
    std::string estimates_file = "catalyst.estimates"; ///< Path to the work estimates file.
#endif
#if FF_cbe__logging
    std::string build_log_file;                        ///< Path to emit build stdout/stderr.
#endif
};

/**
 * @brief Orchestrates the execution of the build graph.
 *
 * This class handles dependency analysis, parallel execution of build steps,
 * and supporting operations like cleaning or generating a compilation database.
 */
class Executor {
public:
    Executor(CBEBuilder &&builder, const ExecutorConfig &config);

    /**
     * @brief Executes the build.
     *
     * Performs a parallel walk of the build graph, executing steps whose
     * dependencies are ready and which need rebuilding.
     *
     * @return Success or error.
     */
    Result<void> execute();

    /**
     * @brief Removes all output files generated by the build steps.
     * @return Success or error.
     */
    Result<void> clean();

    /**
     * @brief Generates a compile_commands.json file for tooling integration.
     * @return Success or error.
     */
    Result<void> emit_compdb();

    /**
     * @brief Prints a Graphviz DOT representation of the build graph to stdout.
     * @return Success or error.
     */
    Result<void> emit_graph();

    /**
     * @brief Prints the actual commands that would be executed to stdout.
     * @return Success or error.
     */
    Result<void> emit_commands();

private:
    struct ExecuteContext; // Forward declaration

    bool needs_rebuild(const BuildStep &step, StatCache &stat_cache, const ToolchainFlags &flags, uint64_t *out_hash = nullptr) const;
    JSON buildCompdb(const std::vector<size_t> &order, const BuildGraph &build_graph) const;
    std::vector<std::string> build_command_args(const BuildStep &step, bool dry_run_mode, const ToolchainFlags &flags) const;
    void print_message(const BuildStep &step, ExecuteContext& ctx, bool is_tty) const;
    int process_step(size_t node_idx, ExecuteContext& ctx, StatCache& stat_cache, bool is_tty) const;
    void worker_loop(ExecuteContext& ctx, StatCache& stat_cache, bool is_tty, size_t thread_count);
    void push_ready(size_t idx, ExecuteContext& ctx);

    CBEBuilder builder;
    ExecutorConfig config;
#if FF_cbe__estimates
    std::unique_ptr<WorkEstimate> estimator;
#endif
    std::vector<std::jthread> pool;
};
} // namespace catalyst
