#pragma once
#include "cob/builder.hpp"
#include "cob/graph.hpp"
#include "cob/utility.hpp"
#if FF_cob__estimates
#include "cob/work_estimate.hpp"
#endif

#include <array>
#include <shared_mutex>
#include <span>
#include <string>
#include <thread>
#include <vector>

namespace catalyst {

#if FF_cob__json_impl
struct JSON;
#endif

struct ToolchainFlags {
    std::span<const std::string> cc;
    std::span<const std::string> cxx;
    std::span<const std::string> linker;
    std::span<const std::string> archiver;
    std::span<const std::string> cflags;
    std::span<const std::string> cxxflags;
    std::span<const std::string> ldflags;
    std::span<const std::string> ldlibs;
};

/**
 * @brief Thread-safe cache for file status information (modification times).
 *
 * This cache prevents redundant filesystem calls when checking multiple dependencies
 * for the same file across different threads.
 */
class StatCache {
    struct Entry {
        std::filesystem::path path;
        std::filesystem::file_time_type time;
        std::error_code ec;

        bool operator<(const Entry &other) const;
        bool operator<(const std::filesystem::path &other_path) const;
    };

    struct Bucket {
        std::vector<Entry> entries;
        std::shared_mutex mtx;
    };

    static constexpr size_t NUM_BUCKETS = 128;
    std::array<Bucket, NUM_BUCKETS> buckets;

    [[nodiscard]] static size_t getBucketIndex(const std::filesystem::path &p) {
        return std::hash<std::filesystem::path::string_type>{}(p.native()) % NUM_BUCKETS;
    }

public:
    /**
     * @brief Retrieves the last write time for a path, caching the result.
     * @param p The file path to check.
     * @return A pair containing the last write time and any error code.
     */
    std::pair<std::filesystem::file_time_type, std::error_code> getOrUpdate(const std::filesystem::path &p);

    /**
     * @brief Checks if an input file has changed since a given output timestamp.
     * @param input The input file path.
     * @param output_time The timestamp of the output file.
     * @return True if input is newer or stat failed, false otherwise.
     */
    bool changedSince(const std::filesystem::path &input, std::filesystem::file_time_type output_time);

    /**
     * @brief Drops any cached entry for a path so the next query re-stats the file.
     *
     * Must be called after a build step rewrites its output: an intermediate artifact
     * (e.g. a `.o` or `.a`) is both the output of one step and the input of a downstream
     * step, and its modtime may have been cached (with a now-stale value) before the
     * rebuild. Without invalidation the downstream step would see the pre-build time and
     * skip its own rebuild.
     * @param p The file path to invalidate.
     */
    void invalidate(const std::filesystem::path &p);

    /**
     * @brief Returns the number of entries in the cache (primarily for unit tests).
     */
    [[nodiscard]] size_t getCacheSize() const;
};

struct ExecutorConfig {
    bool dry_run = false;                      ///< If true, print commands without executing.
    bool clean = false;                        ///< If true, clean artifacts instead of building.
    bool clean_cc_only = false;                ///< If true, only clean cc and cxx steps.
    bool silent = false;                       ///< If true, suppress all output except errors.
    bool keep_going = false;                   ///< If true, continue building other steps after an error.
    size_t jobs = 0;                           ///< Number of parallel jobs (0 = auto-detect).
    std::string build_file = "catalyst.build"; ///< Path to the build manifest.
#if FF_cob__estimates
    std::string estimates_file = "catalyst.estimates"; ///< Path to the work estimates file.
#endif
#if FF_cob__logging
    std::string build_log_file; ///< Path to emit build stdout/stderr.
#endif
};

/**
 * @brief Orchestrates the execution of the build graph.
 *
 * This class handles dependency analysis, parallel execution of build steps,
 * and supporting operations like cleaning or generating a compilation database.
 */
class Executor {
public:
    Executor(COBBuilder &&builder, ExecutorConfig config);

    /**
     * @brief Executes the build.
     *
     * Performs a parallel walk of the build graph, executing steps whose
     * dependencies are ready and which need rebuilding.
     *
     * @return Success or error.
     */
    Result<void> execute();

    /**
     * @brief Removes all output files generated by the build steps.
     * @return Success or error.
     */
    Result<void> clean();

    /**
     * @brief Generates a compile_commands.json file for tooling integration.
     * @return Success or error.
     */
    Result<void> emitCompDB();

    /**
     * @brief Prints a Graphviz DOT representation of the build graph to stdout.
     * @return Success or error.
     */
    Result<void> emitGraph();

    /**
     * @brief Prints the actual commands that would be executed to stdout.
     * @return Success or error.
     */
    Result<void> emitCommands();

private:
    struct ExecuteContext; // Forward declaration

    bool needsRebuild(const BuildStep &step,
                       StatCache &stat_cache,
                       const ToolchainFlags &flags,
                       uint64_t *out_hash = nullptr,
                       std::vector<std::string> *out_args = nullptr) const;

    [[nodiscard]] std::vector<std::string>
    buildCommandArgs(const BuildStep &step, bool dry_run_mode, const ToolchainFlags &flags) const;
    void printMessage(const BuildStep &step, ExecuteContext &ctx, bool is_tty) const;
    int processStep(size_t node_idx, ExecuteContext &ctx, StatCache &stat_cache, bool is_tty) const;
    void workerLoop(ExecuteContext &ctx, StatCache &stat_cache, bool is_tty, size_t thread_count);
#if FF_cob__estimates
    static void pushReady(size_t idx, ExecuteContext &ctx, WorkEstimate *estimator);
#else
    static void pushReady(size_t idx, ExecuteContext &ctx, void *estimator);
#endif

    COBBuilder builder;
    ExecutorConfig config;
#if FF_cob__estimates
    std::unique_ptr<WorkEstimate> estimator;
#endif
    std::vector<std::jthread> pool;
};
} // namespace catalyst
